apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
  name: backend-bookstore
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: backend
      kubernetes.io/metadata.name: bookstore
---
kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: backend-bookstore-repo-sync
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/shumiao/gke-fleet-examples
    branch: main
    dir: config-management/configs/backend/bookstore/team-managed-configs
    auth: none

---
# Give repo sync reconciler permissions to manage the k8s objects.
 kind: RoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: repo-sync-reconciler-cluster-role-binding
   namespace: bookstore
 subjects:
 - kind: ServiceAccount
   name: ns-reconciler-bookstore-backend-bookstore-repo-sync-27
   namespace: config-management-system
 roleRef:
   kind: ClusterRole
   name: edit
   apiGroup: rbac.authorization.k8s.io
