apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shoe-server-applicationset
spec:
  generators:
  - clusters:
      selector: 
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          createdBy: argocd-fleet-syncer:
          fleetScope: frontend
  template:
    metadata:
      name: '{{name}}-shoe-server' 
    spec:
      project: default
      source:
        repoURL: https://github.com/shumiao/gke-fleet-examples
        targetRevision: HEAD
        path: fleet-and-argocd/shoe-server-application/manifests
      destination:
        server: '{{server}}'
        namespace: shoestore
