apiVersion: v1
kind: Secret
metadata:
  name: tf-cluster-1-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: tf-cluster-1
  server: https://container.googleapis.com/v1/projects/shumiao-test/locations/us-cental1/clusters/tf-cluster-1
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
