apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webserver-applicationset
  namespace: argocd
spec:
  generators:
  - clusters:
      selector: 
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          createdBy: argocd-fleet-syncer
          # Targeting at clusters where the "frontend" team has a presence.
          fleetScope: frontend
  template:
    metadata:
      name: '{{name}}-webserver' 
    spec:
      project: default
      source:
        # A source repo and path that the "frontend" team has write access to. 
        repoURL: https://github.com/shumiao/gke-fleet-examples
        targetRevision: HEAD
        path: fleet-and-argocd/webserver-application/manifests
      destination:
        server: '{{server}}'
        # Only syncing into the "webserver" fleet namespace.
        namespace: webserver
  syncPolicy:
    # The controller will delete Applications when the ApplicationSet is deleted.
    preserveResourcesOnDeletion: false
