apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-web-server 
  namespace: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-web-server 
  template:
    metadata:
      labels:
        app: demo-web-server 
    spec:
      containers:
      - name: demo-web-server 
        image: us-central1-docker.pkg.dev/shumiao-test/demo-web-server/demo-web-server:v2.0
        ports:
        - containerPort: 8888 # Expose port 8888 of the container
